mycompounds <- c("S-adenosyl homocysteine",
                 "Propionyl-L-carnitine",
                 "Arginine",
                 "Tryptophan", 
                 "Proline betaine",
                 "Tyrosine",
                 "Asparagine",
                 "Homarine",
                 "Tryptophan", 
                 "Butyryl carnitine",
                 "Glutamic acid",
                 "Glutathione disulfide",
                 "GMP",
                 "Homoserine", 
                 "Calligonine", 
                 "Glycerophosphocholine",
                 "MTA",
                 "Glycine betaine")